### ISSUE TITLE
Crashing on images due to relative/absolute path mixture

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-unece#32]
@opoudjis surely you know what this is: 😉 

Occurs here: 
https://github.com/metanorma/mn-samples-un

```
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/bin/metanorma)
Errno::ENOENT: No such file or directory @ rb_sysopen - sources/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/image20191208-39032-g43y8p.png
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/image_size-2.0.2/lib/image_size.rb:46:in `initialize'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/image_size-2.0.2/lib/image_size.rb:46:in `open'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/image_size-2.0.2/lib/image_size.rb:46:in `path'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/html2doc-0.9.2/lib/html2doc/mime.rb:68:in `image_resize'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.8/lib/isodoc/word_function/postprocess.rb:54:in `block in word_admonition_images'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.8/lib/isodoc/word_function/postprocess.rb:52:in `word_admonition_images'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.8/lib/isodoc/word_function/postprocess.rb:64:in `word_cleanup'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.8/lib/isodoc/word_function/postprocess.rb:42:in `toWord'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.8/lib/isodoc/word_function/postprocess.rb:36:in `postprocess'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.8/lib/isodoc/convert.rb:179:in `convert'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.8/lib/isodoc/word_convert.rb:34:in `convert'
```

**Comment by ronaldtse** [comment]
Highlight:
```
sources/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/image20191208-39032-g43y8p.png
```
